apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: shopsphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: mohdayazz/shopsphere-product-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: "5002"
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "test123"
            - name: DB_NAME
              value: "shopsphere"
